name: Build
on:
  push:
    branches:
      - typescript-nodejs-patch-1
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code repository source code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            jupiterone/codeql
          tags: |
            type=sha
            
      - name: debug
        run: echo ${{ steps.meta.outputs.tags }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          tags: jupiterone/codeql:latest

